#Call the necessary libraries (This must be done each time you re-open R)
library(readr)
library(dplyr)
library(ggplot2)
library(ggpubr)

#Import the turtle data from github. Here, each row represents an individual turtle. 

turtle_data <- read_csv("https://raw.githubusercontent.com/LukeZingg/Turtle-Plastic-Ingestion-Data-and-Code/refs/heads/main/Plastic%20Data-Data%20from%20Individual%20Turtles.csv")

#Makes the column names seperated by periods instead of spaces
names(turtle_data) <- make.names(names(turtle_data))

#Filter out na.values of our variable of interest. 
#If we want to re-examine a different variable we can re-run the previous line of codes to get the data without the na values removed.
turtle_data <-  turtle_data %>% filter(!is.na(Number.of.Trash.Items))

#Convert Number.of.Trash.Items into numeric values. 
turtle_data$Number.of.Trash.Items <- as.numeric(turtle_data$Number.of.Trash.Items)

#Histogram of the number of trash items. 
ggplot(turtle_data, aes(x = Number.of.Trash.Items)) +
  geom_histogram(fill = "#0072B2", color = "white", bins = 30) +
  labs(
    title = "Distribution of Number of Trash Items Found in Sea Turtles",
    x = "Number of Trash Items",
    y = "Frequency"
  ) +
  scale_x_continuous(breaks = seq(0,120,by = 10))+
  theme_classic(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold"),
    axis.text = element_text(color = "black"),
    axis.title = element_text(color = "black", face = "bold")
  )


bootstrap_trash_mean <- function(data = turtle_data$Number.of.Trash.Items, 
                                 R = 10000, 
                                 alpha = 0.05) {
  
  #We can generate different simulations by changing this seed. 
  set.seed(123)
  
  # Preallocate vector for storing bootstrapped means
  bootstrap_means <- numeric(R)
  
  for (i in 1:R) {
    sample_i <- sample(data, size = length(data), replace = TRUE)
    bootstrap_means[i] <- mean(sample_i)
  }
  
  # Compute percentile confidence interval
  ci_bounds <- quantile(bootstrap_means, probs = c(alpha / 2, 1 - alpha / 2))
  
  # Create data frame for plotting
  boot_df <- data.frame(mean_trash = bootstrap_means)
  boot_df$ci_region <- case_when(
    boot_df$mean_trash < ci_bounds[1] ~ "Outside CI",
    boot_df$mean_trash > ci_bounds[2] ~ "Outside CI",
    TRUE ~ "Inside CI"
  )
  
  # Plot the bootstrap distribution of the mean
  ggplot(boot_df, aes(x = mean_trash, fill = ci_region)) +
    geom_histogram(bins = 50, color = "black", alpha = 0.8) +
    scale_fill_manual(values = c(
      "Inside CI" = "#dc5318",
      "Outside CI" = "#5c89a6"
    )) +
    labs(
      title = "Distribution of Resampled Mean Trash Items in Sea Turtles",
      subtitle = paste0((1 - alpha) * 100, "% CI: [", 
                        round(ci_bounds[1], 2), ", ", round(ci_bounds[2], 2), "] items"),
      x = "Resampled Mean Trash Count Values",
      y = "Frequency"
    ) +
    theme_classic(base_size = 14) +
    theme(
      panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
      axis.text = element_text(color = "black"),
      axis.title = element_text(color = "black", face = "bold"),
      plot.title = element_text(color = "black", face = "bold", size = 16),
      plot.subtitle = element_text(color = "black", size = 12),
      legend.position = "none"
    )
}

# Run it!
bootstrap_trash_mean(alpha = 0.05, R = 10000)

#We can compare this to the interval generated by the parametric method. 
#Though our data is highly skewed, it's large sample size (N = 464) allows the 
#parametric methods using the Central Limit Theorem to be accurate generating 
#a similar interval to the bootstrap method. 

t.test(turtle_data$Number.of.Trash.Items)

#Import the second dataset from github. In this case, each row is an individual piece of trash. 

trash_data <- read_csv("https://raw.githubusercontent.com/LukeZingg/Turtle-Plastic-Ingestion-Data-and-Code/refs/heads/main/Turtle%20Data-Data%20from%20Pieces%20of%20Trash.csv")

names(trash_data) <- make.names(names(trash_data))

#We can continue our analysis by analysing the data from individual pieces of trash. 
#You can easily adapt the previous code to bootstrap for a variable in this new dataset!
